--[[
[
🔴WARNING🔴:
PROBALY THE SCRIPT WILL 🟡BAN YOU🟡, CAUSE I DID NOT TEST IT OUT THIS MONTH, SO ITS PROBALY PATCHED.
🔴MAKE SURE YOU EXECUTE ON ALT🔴.
🟢IF IT IS BANNING YOU, MESSAGE ME ON DISCORD ABOUT IT🟢
]
Good luck i guess❓
]]--
